'use client';

import React, { useState } from 'react';
import {
  X,
  Download,
  Printer,
  Copy,
  Check,
  Sparkles,
  ShieldCheck
} from 'lucide-react';
import { DocumentAnalysis } from '@/lib/types';

interface ExportModalProps {
  doc: DocumentAnalysis;
  isOpen: boolean;
  onClose: () => void;
}

export default function ExportModal({ doc, isOpen, onClose }: ExportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const markdownContent = `# DocFin Executive Document Audit Memo
**Document:** ${doc.name}
**Domain:** ${doc.detectedDomain.toUpperCase()} (${doc.confidenceScore}% confidence)
**Audited At:** ${doc.uploadedAt}

---

## 1. Executive Summary
${doc.summary.tldr}

## 2. Key Findings & Extracted Takeaways
${doc.summary.keyTakeaways.map((k) => `- ${k}`).join('\n')}

## 3. Financial & Risk Metrics
${doc.metrics.map((m) => `- **${m.label}:** ${m.value} (${m.subtext || ''})`).join('\n')}

## 4. Priority Action Checklist
${doc.summary.actionChecklist.map((a) => `- [${a.completed ? 'x' : ' '}] **[${a.priority.toUpperCase()}]** ${a.text}`).join('\n')}

---
*Generated by DocFin Multimodal Document Intelligence Platform*
`;

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${doc.name.replace(/\.[^/.]+$/, '')}_DocFin_Audit.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/65 backdrop-blur-2xl animate-in fade-in select-none">
      {/* Liquid Glass Modal Window */}
      <div className="liquid-glass-modal rounded-[32px] max-w-2xl w-full text-white overflow-hidden flex flex-col max-h-[88vh] animate-in zoom-in-95 duration-250 relative group">
        {/* Ambient Fluid Glow */}
        <div className="absolute top-0 left-1/3 w-64 h-44 bg-blue-500/20 rounded-full blur-3xl pointer-events-none -z-10" />
        <div className="absolute bottom-0 right-1/3 w-64 h-44 bg-indigo-500/20 rounded-full blur-3xl pointer-events-none -z-10" />

        {/* Modal Header */}
        <div className="p-6 px-7 border-b border-white/[0.12] flex items-center justify-between bg-white/[0.02] flex-shrink-0">
          <div className="flex items-center gap-3.5">
            <div className="w-11 h-11 rounded-2xl bg-gradient-to-tr from-blue-600/30 to-indigo-500/20 border border-white/20 flex items-center justify-center text-blue-300 shadow-[inset_0_1px_1px_rgba(255,255,255,0.4)]">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base sm:text-lg font-bold text-white tracking-tight">
                Export Executive Audit Memo
              </h3>
              <p className="text-xs text-slate-300/80 mt-0.5">
                Download or print verified synthesis of <span className="text-blue-300">{doc.name}</span>
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-9 h-9 rounded-full bg-white/5 hover:bg-white/15 border border-white/10 flex items-center justify-center text-slate-300 hover:text-white transition-all cursor-pointer backdrop-blur-md hover:scale-105"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Memo Preview Box */}
        <div className="p-6 overflow-y-auto bg-black/40 text-slate-200 text-xs font-mono whitespace-pre-wrap border-b border-white/[0.08] leading-relaxed max-h-96">
          {markdownContent}
        </div>

        {/* Actions Footer */}
        <div className="p-5 px-7 border-t border-white/[0.12] bg-white/[0.02] backdrop-blur-2xl flex flex-wrap items-center justify-between gap-3 flex-shrink-0">
          <span className="text-xs text-slate-300/80 flex items-center gap-1.5 font-mono">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            DocFin Verified Audit Signature Attached
          </span>

          <div className="flex items-center gap-2.5">
            <button
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-4 py-2 rounded-full text-xs font-semibold bg-white/5 hover:bg-white/15 border border-white/10 text-white transition-all cursor-pointer"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-4 py-2 rounded-full text-xs font-semibold bg-white/5 hover:bg-white/15 border border-white/10 text-white transition-all cursor-pointer"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>

            <button
              onClick={handleDownloadMarkdown}
              className="liquid-glass-button flex items-center gap-1.5 px-5 py-2 rounded-full text-xs font-bold text-white transition-all cursor-pointer hover:scale-105 active:scale-95"
            >
              <Download className="w-3.5 h-3.5 text-white" />
              <span>Download .md</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
